[project]
name = "volunteer-scraper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "pandas>=3.0.0",
    "playwright>=1.58.0",
    "pgeocode>=0.4.0",
]
